# Nome da Actions:  
name:cobra

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: matheus-richard #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Retornando na opção Ação de execução do fluxo de trabalho, clique em “Executar:

Repositório

Pasta dos arquivos:
Em seu repositorio cliente em main e selecione uma saída de branch:
resultado

E aqui estão os arquivos gerados que você pode usar como bem entender:

Arquivos

Código Github para uso:

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Discussão (0)
Se inscrever
foto
Adicionar à discussão
Código de Conduta • Denunciar abuso
Leia a seguir
imagem de perfil de mohsenkamrani
Contribuição de código aberto, um guia para iniciantes (em 2 minutos).
mohsen -9 de julho

shivam164 imagem de perfil
Comandos Git ( para facilitar seu desenvolvimento 🤗 )
Shivam -23 de junho

imagem de perfil codewithmmak
Tutorial Git e GitHub para iniciantes
Ajaz Khan -9 de julho

imagem de perfil de cicirello
O GitHub Action do gerador de crachás jacoco agora também está disponível como uma ferramenta CLI do PyPI
Vicente A. Cicirello -8 de julho


Henrique Lopes
Seguir
"Não há razão alguma em usar a palavra "impossível" para descrever algo que possa ser claramente verificado."
INGRESSOU
5 de conjunto. de 2021
Tendências na Comunidade DEV 
Imagem do perfil de Ben Halpern
Projeto paralelo domingo! Como tá indo?
# showdev # sideprojects # debate # watercooler
Imagem de perfil de Sloan
Explique a diferença entre shell, console, terminal, linha de comando, etc. como se eu tivesse cinco anos
# anônimo # discuta # ajuda
Imagem do perfil de Keff
Você não fará isso mais tarde (provavelmente) - sou um procrastinador, eu sei
# programação # discuta # watercooler # produtividade
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: matheus-richard #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
